  version: '3'
  services:
    database:
      image: 'postgres:latest'
      volumes:
        - ./db-data/:/var/lib/postgresql/data/
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 244629933
        POSTGRES_DB: FashionBlog